# action.yml
name: 'Infisical Loader'
author: Fritz Larco
description: 'Load your Infisical Secrets into your Github Actions workflow'

inputs:
  version:
    description: 'The CLI version to use (e.g. 0.28.1). Check https://github.com/Infisical/infisical/tags'
    required: true
  
  client_id:
    description: 'The client-id value, typically secrets.INFISICAL_CLIENT_ID'
    required: true

  client_secret:
    description: 'The client-secret value, typically secrets.INFISICAL_CLIENT_SECRET'
    required: true

  project_id:
    description: 'The project-id or workspace-id value. If not set, will use workspaceId in .infisical.json'
    required: false

  env:
    description: The environment to use. If not set, will use .infisical.json
    required: false

  path:
    description: 'The secrets path value'
    required: false

  dotenv:
    description: 'Create a .env file in the root folder. Accepts `true` or `false`'
    required: false

  dotenv_sh:
    description: 'Create a .env.sh file in the root folder. Accepts `true` or `false`'
    required: false
    
runs:
  using: 'composite'
  timeout-minutes: 5
  steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - name: Load Secrets (Linux)
        shell: bash
        env:
          INFISICAL_CLIENT_ID: ${{ inputs.client_id }}
          INFISICAL_CLIENT_SECRET: ${{ inputs.client_secret }}
          INFISICAL_PROJECT_ID: ${{ inputs.project_id }}
          INFISICAL_ENV: ${{ inputs.env }}
          INFISICAL_PATH: ${{ inputs.path }}
          INFISICAL_VERSION: ${{ inputs.version }}
          DOTENV: ${{ inputs.dotenv }}
          DOTENV_SH: ${{ inputs.dotenv_sh }}
        if: runner.os == 'linux'
        run: bash infisical-linux.sh

      - name: Load Secrets (Mac)
        shell: bash
        env:
          INFISICAL_CLIENT_ID: ${{ inputs.client_id }}
          INFISICAL_CLIENT_SECRET: ${{ inputs.client_secret }}
          INFISICAL_PROJECT_ID: ${{ inputs.project_id }}
          INFISICAL_ENV: ${{ inputs.env }}
          INFISICAL_PATH: ${{ inputs.path }}
          INFISICAL_VERSION: ${{ inputs.version }}
          DOTENV: ${{ inputs.dotenv }}
          DOTENV_SH: ${{ inputs.dotenv_sh }}
        if: runner.os == 'macOS'
        run: bash infisical-mac.sh

      - name: Load Secrets (Windows)
        shell: pwsh
        env:
          INFISICAL_CLIENT_ID: ${{ inputs.client_id }}
          INFISICAL_CLIENT_SECRET: ${{ inputs.client_secret }}
          INFISICAL_PROJECT_ID: ${{ inputs.project_id }}
          INFISICAL_ENV: ${{ inputs.env }}
          INFISICAL_PATH: ${{ inputs.path }}
          INFISICAL_VERSION: ${{ inputs.version }}
          DOTENV: ${{ inputs.dotenv }}
          DOTENV_SH: ${{ inputs.dotenv_sh }}
        if: runner.os == 'windows'
        run: .\infisical-windows.ps1

branding:
  color: black
  icon: zap